### ISSUE TITLE
Value changed in Stweaks doesn't save

### ISSUE THREAD

**Issue by yxliang01** [Tkkg1994/IronRom#1]
Hello, I had been using Ironrom for many months and I find it fantastic! However, After I had patched the IronKernel on my Tab, the charging is extremely slow. I found it is a problem of the kernel parameter, the input currents are set too low. When I attempted to change and applied it, it didn't change anything at all (after restarting the Stweaks, it shows the old value). This rom would be perfect if this problem is fixed. (Device: T805 Lollipop)

**Comment by Tkkg1994** [comment]
This is just a busybox problem, the only thing you have to do: Uninstall all busybox you got at the moment and install busybox on rails from the playstore, hit clean and install, done

**Comment by yxliang01** [comment]
It seems work! Thank You. But could you tell me what's the root of this problem? Since the busybox was installed with IronRom.
